### ISSUE TITLE
下载的v1.1版本，conf 通过，make的时候报错

### ISSUE THREAD

**Issue by yuchen99** [swoole/php-cp#10]
/bin/bash /opt/phpdevelop/php-cp-1.1/libtool --mode=compile cc  -I. -I/opt/phpdevelop/php-cp-1.1 -DPHP_ATOM_INC -I/opt/phpdevelop/php-cp-1.1/include -I/opt/phpdevelop/php-cp-1.1/main -I/opt/phpdevelop/php-cp-1.1 -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -I/opt/phpdevelop/php-cp-1.1/include  -DHAVE_CONFIG_H  -g -O2   -c /opt/phpdevelop/php-cp-1.1/cpServer.c -o cpServer.lo 
libtool: compile:  cc -I. -I/opt/phpdevelop/php-cp-1.1 -DPHP_ATOM_INC -I/opt/phpdevelop/php-cp-1.1/include -I/opt/phpdevelop/php-cp-1.1/main -I/opt/phpdevelop/php-cp-1.1 -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -I/opt/phpdevelop/php-cp-1.1/include -DHAVE_CONFIG_H -g -O2 -c /opt/phpdevelop/php-cp-1.1/cpServer.c  -fPIC -DPIC -o .libs/cpServer.o
/opt/phpdevelop/php-cp-1.1/cpServer.c: In function 'cpServer_master_onAccept':
/opt/phpdevelop/php-cp-1.1/cpServer.c:315:69: error: 'EPOLLIN' undeclared (first use in this function)
         if (cpEpoll_add(CPGS->reactor_threads[c_pti].epfd, conn_fd, EPOLLIN | EPOLLRDHUP | EPOLLHUP | EPOLLERR | EPOLLPRI) < 0) {
                                                                     ^
/opt/phpdevelop/php-cp-1.1/cpServer.c:315:69: note: each undeclared identifier is reported only once for each function it appears in
/opt/phpdevelop/php-cp-1.1/cpServer.c:315:79: error: 'EPOLLRDHUP' undeclared (first use in this function)
         if (cpEpoll_add(CPGS->reactor_threads[c_pti].epfd, conn_fd, EPOLLIN | EPOLLRDHUP | EPOLLHUP | EPOLLERR | EPOLLPRI) < 0) {
                                                                               ^
/opt/phpdevelop/php-cp-1.1/cpServer.c:315:92: error: 'EPOLLHUP' undeclared (first use in this function)
         if (cpEpoll_add(CPGS->reactor_threads[c_pti].epfd, conn_fd, EPOLLIN | EPOLLRDHUP | EPOLLHUP | EPOLLERR | EPOLLPRI) < 0) {
                                                                                            ^
/opt/phpdevelop/php-cp-1.1/cpServer.c:315:103: error: 'EPOLLERR' undeclared (first use in this function)
         if (cpEpoll_add(CPGS->reactor_threads[c_pti].epfd, conn_fd, EPOLLIN | EPOLLRDHUP | EPOLLHUP | EPOLLERR | EPOLLPRI) < 0) {
                                                                                                       ^
/opt/phpdevelop/php-cp-1.1/cpServer.c:315:114: error: 'EPOLLPRI' undeclared (first use in this function)
         if (cpEpoll_add(CPGS->reactor_threads[c_pti].epfd, conn_fd, EPOLLIN | EPOLLRDHUP | EPOLLHUP | EPOLLERR | EPOLLPRI) < 0) {
                                                                                                                  ^
/opt/phpdevelop/php-cp-1.1/cpServer.c: In function 'cpReactor_thread_loop':
/opt/phpdevelop/php-cp-1.1/cpServer.c:533:13: error: 'EPOLLIN' undeclared (first use in this function)
     handles[EPOLLIN] = cpReactor_client_receive;
             ^
/opt/phpdevelop/php-cp-1.1/cpServer.c:534:13: error: 'EPOLLPRI' undeclared (first use in this function)
     handles[EPOLLPRI] = cpReactor_client_release;
             ^
/opt/phpdevelop/php-cp-1.1/cpServer.c: In function 'cpReactor_start':
/opt/phpdevelop/php-cp-1.1/cpServer.c:548:40: error: 'EPOLLIN' undeclared (first use in this function)
     if (cpEpoll_add(accept_epfd, sock, EPOLLIN) < 0) {
                                        ^
make: *** [cpServer.lo] Error 1

**Comment by GXhua** [comment]
你用的是freebsd系统？   目前cp只支持linux

**Comment by yuchen99** [comment]
抱歉，没有系统信息
php版本
```
PHP 5.5.9-1ubuntu4.6 (cli) (built: Feb 13 2015 19:17:11) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```
系统是ubuntu 14.04

**Comment by GXhua** [comment]
麻烦你用master版本 试下呢？

**Comment by GXhua** [comment]
不好意思  才找到原因 修复了  试下吧
