### ISSUE TITLE
gone away......

### ISSUE THREAD

**Issue by lockfan** [swoole/php-cp#13]
在使用过程中若出现gone away，则需要重启pool_server才能继续访问DB；

服务器设置timeout为60s，由于需要过渡阶段，mysql依然会接受若干短连接，所以不能通过修改wait_timeout和interactive_timeout来解决问题，可有解决方案？

**Comment by GXhua** [comment]
在pdo框架层做下兼容，如果gone away就再获得一次链接，pool_server底层判断如果gone away了会把这个链接踢掉重新连的。

**Comment by lockfan** [comment]
....
$succ = $stmt->execute();

if (!$succ) {
	//check if gone away...
	if ($this->error[‘code'] == 2006 && extension_loaded('connect_pool')) {
		self::$DB = new pdo_connect_pool(...);
		//prepare & re_execute
		//err_2006 anyway...
	}
}

这样处理，还是会继续gone away呢

**Comment by GXhua** [comment]
我没实现error code     我目前是直接匹配$e->getmessage()中的gone away关键字来实现的 不是很严谨  暂时没时间优化
