### ISSUE TITLE
长时间空闲之后出错

### ISSUE THREAD

**Issue by xavieryang007** [swoole/php-cp#15]
我用ab 测试并发访问页面，数据池在并发下没有出错。当并发停止之后一段时间，出现下面错误。代码用的源码中的测试代码。ab -c 1000 -n 10000
Fatal error: Call to a member function fetchAll() on a non-object in

**Comment by GXhua** [comment]
应该是gone away了   pool和mysql之间的连接长时间不用会被mysql踢掉的，把mysql的session timeout时间调长试试

**Comment by xavieryang007** [comment]
好的 我测试下

**Comment by luoxun** [comment]
建立把 mysql gnone away 做一个异常出来,指定 code 这样 发现如果是 gnone away 好用这个code 重连,我看了一下 源码 没有发现自定义 异常 所以我们现在用这个连接池是 一个大的 exception 来catch 住重连.总觉得这样不是很好?

**Comment by GXhua** [comment]
恩确实像你说那样，目前没有把code这块做到和原生一样，目前我们也是cacth  发现如果是gone away就重连，我抽时间实现下

**Comment by luoxun** [comment]
方便加一下 QQ 么? 遇到点问题 想请教 qq 313451277
