### ISSUE TITLE
php7下重装了php-cp失败

### ISSUE THREAD

**Issue by taozywu** [swoole/php-cp#17]
NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library '/data/program/php/lib/php/extensions/no-debug-non-zts-20141001/connect_pool.so' - /data/program/php/lib/php/extensions/no-debug-non-zts-20141001/connect_pool.so: undefined symbol: zval_used_for_init in Unknown on line 0
---
who can help me ?

**Comment by taozywu** [comment]
从网上找到类似答复：
（二）兼容问题
1 当给php7安装扩展的时候发现报错 error: ext/standard/php_smart_str.h: No such file or directory
之前给php5.6.7安装这个扩展的时候是没有问题的，于是我搜索了一下
➜ find / -name php_smart_str.h
/usr/local/php/include/php/ext/standard/php_smart_str.h
/usr/local/src/php-5.4.35/ext/standard/php_smart_str.h
/usr/local/src/php-5.6.7/ext/standard/php_smart_str.h
看结果两个源包中都有这个文件 当前安装的php目录里面也有这个文件 但是php7的源包和安装目录中都没有这个文件
➜ ~ ls /usr/local/src/php-5.6.7/ext/standard | grep php_smart_str
php_smart_str.h
php_smart_str_public.h
➜ ~ ls ~/Downloads/php-7.0.0alpha1/ext/standard | grep php_smart_str
php_smart_string.h
php_smart_string_public.h
看这个名字在php7的源码包中有php_smart_string.h这个文件 用Bcompare对比了俩文件 差很多
且不说这个源文件是什么作用，老版本有而php7源包里面没有，这应当算是个兼容性问题

**Comment by GXhua** [comment]
暂时不支持php7呢。。

**Comment by taozywu** [comment]
好吧.......
