### ISSUE TITLE
请问redis 支持 multi() 吗？

### ISSUE THREAD

**Issue by kenshin1983** [swoole/php-cp#19]
$redis = new redis_connect_pool();
$redis->connect('127.0.0.1', 6379, 0.5);
$ret = $redis->multi()
->lrange($k1, 0, -1)
->lrange($k2, 0, -1)
->lrange($k3, 0, -1)
->exec();

报错PHP Fatal error:  Call to a member function lrange() on a non-object in ********

**Comment by GXhua** [comment]
暂不支持~

**Comment by GXhua** [comment]
不是不支持这种事务 而是用法不支持连续->   你可以$redis->multi();$redis->lrange();$redis->lrange();$redis->exec();
