### ISSUE TITLE
为毛非得root？

### ISSUE THREAD

**Issue by dingpiao** [swoole/php-cp#21]
root，没法放fpm,只能放cli了，那用处小多了

**Comment by reallovelei** [comment]
pool_server是在cli下 启动的，client是可以在fpm连接    server的。

**Comment by dingpiao** [comment]
那有个问题，pool_server用root启动，我用其它账户调用pool_server, 报
PHP Fatal error:  redis_connect_pool::__call(): open error Error: Permission denied [13]

**Comment by dingpiao** [comment]
用root调用就没问题。

**Comment by dingpiao** [comment]
应该是selinux策略的问题，多谢!

**Comment by GXhua** [comment]
fpm需要有/tmp目录的写权限
