### ISSUE TITLE
多个MySQL和Redis链接时Auth丢失的问题

### ISSUE THREAD

**Issue by mougeli** [swoole/php-cp#22]
现在建立2个Redis池和3个MySQL池，当1个MySQL池和2个Redis池连接时，使用正常，当第2个MySQL池中链接建立时，所有的Redis链接的Auth都立即失效且无法重新建立。

**Comment by mougeli** [comment]
求解，十分疑惑~

**Comment by GXhua** [comment]
我试了下没有重现  能不能写个脚本给我
