### ISSUE TITLE
PID没有生成

### ISSUE THREAD

**Issue by aimpsmile** [swoole/php-cp#23]
ini_set('memory_limit', '300M'); //防止扩展有内存泄露，超过10000次请求重启代理进程
ini_set("display_errors", "On");
define("PID_PRE", "/usr/local/php/var/run/redis_pool_");
$conf = "/usr/local/php/etc/pool.ini"; //pool_server的配置文件
用root执行的 ./pool_server start
进程都存在，是不是还有什么需要注意的。

**Comment by GXhua** [comment]
/usr/local/php/var/run 这个路径存在吗

**Comment by aimpsmile** [comment]
这个目录存在，而且权限是777

**Comment by GXhua** [comment]
restart 提示找不到pid？

**Comment by aimpsmile** [comment]
Warning: file_get_contents(/tmp/redis_pool_.pid): failed to open stream: No such file or directory in /home/www/test_website/pool_server on line 30

**Comment by GXhua** [comment]
/usr/local/php/var/run/redis_pool_.pid  应该找这个才对啊  你qq多少  ？

**Comment by aimpsmile** [comment]
我换成/tmp下了。也还一样。确认找这个目录

**Comment by aimpsmile** [comment]
我的企鹅：2850774126

**Comment by GXhua** [comment]
哦 是这样的  define("PID_PRE", "/var/run/con_pool_");   这个不能变   变了就找不到了 我扩展c代码里面写死了的  外面这个配置不生效  下个版本我改下
