### ISSUE TITLE
General error，可以读，不能写

### ISSUE THREAD

**Issue by lockfan** [swoole/php-cp#38]
PDOProxy：

10.0.0.2 via TCP/IPobject(pdoProxy)#50 (6) {
  ["use_ms"]=>
  bool(false)
  ["config"]=>
  array(1) {
    ["master"]=>
    array(3) {
      ["data_source"]=>
      string(55) "mysql:dbname=order;host=10.0.0.2;port=3306"
      ["username"]=>
      string(10) "write"
      ["pwd"]=>
      string(16) "632tKNDMdSyWM3v4"
    }
  }
  ["in_tran"]=>
  bool(false)
  ["enable_slave"]=>
  bool(true)
  ["data_source"]=>
  string(55) "mysql:dbname=order;host=10.0.0.2;port=3306"
  ["cli"]=>
  resource(54) of type (ConPoolClient)
}

STMT：

object(pdo_connect_pool_PDOStatement)#51 (2) {
  ["cli"]=>
  resource(54) of type (ConPoolClient)
  ["data_source"]=>
  string(55) "mysql:dbname=order;host=10.0.0.2;port=3306"
}

STMT->fetchAll Throws Exception:

exception 'PDOException' with message 'SQLSTATE[HY000]: General error' in /usr/sbin/pool-server:18
Stack trace:
#0 [internal function]: PDOStatement->fetchAll(2)
#1 /usr/sbin/pool-server(18): pool_server_create('/etc/pool-serve...')
#2 {main}

SQL:

        UPDATE order SET `user_id` = ?  WHERE `order_id` = ?"
        
        &array(1) {
          [1]=>
          int(39)
        }
       
        &array(1) {
          [1]=>
          int(292)
        }
        
        &array(1) {
          ["type"]=>
          string(4) "main"
        }

PHP & MYSQL：

[root@TEST ~]# php --version
PHP 5.6.16 (cli) (built: Nov 29 2015 18:13:35)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

[root@TEST ~]# php --ri connect_pool
connect_pool

connect_pool support => enabled
Version => 1.4.6
Author => 郭新华，张磊
email => woshiguo35@sina.com

软件: MySQL
软件版本: 5.5.30-tokudb-7.1.0-log - MySQL Community Server (GPL)

**Comment by GXhua** [comment]
多谢反馈 请提供测试代码

**Comment by lockfan** [comment]
PDONEW

`<?php
/*{{{LICENSE
  +-----------------------------------------------------------------------+
  | SlightPHP Framework                                                   |
  +-----------------------------------------------------------------------+
  | This program is free software; you can redistribute it and/or modify  |
  | it under the terms of the GNU General Public License as published by  |
  | the Free Software Foundation. You should have received a copy of the  |
  | GNU General Public License along with this program.  If not, see      |
  | http://www.gnu.org/licenses/.                                         |
  | Copyright (C) 2008-2009. All Rights Reserved.                         |
  +-----------------------------------------------------------------------+
  | Supports: http://www.slightphp.com                                    |
  +-----------------------------------------------------------------------+
}}}*/

/**
 * @package SlightPHP
 * @subpackage SDb
 */
class Db_PDONEW extends DbObject
{

    /**
     * @var string
     */
    public $host;

    /**
     * @var int
     */
    public $port = 3306;

    /**
     * @var string
     */
    public $user;

    /**
     * @var string
     */
    public $password;

    /**
     * @var string
     */
    public $database;

    /**
     * @var string
     */
    public $pri;

    /**
     * @var string
     */
    public $key;

    /**
     * @var string
     */
    public $dtype;

    /**
     * @var string
     */
    public $charset;

    /**
     * @var string
     */
    public $orderby;

    /**
     * @var string
     */
    public $groupby;

    /**
     * @var string
     */
    public $sql;

    /**
     * @var bool
     */
    public $count = false;

    /**
     * @var int
     */
    public $limit = 0;

    /**
     * @var int
     */
    public $page = 1;

    /**
     * @var string
     */
    private $prefix;

    /**
     * @var string
     */
    private $countsql;

    /**
     * @var int
     */
    private $affectedRows = 0;

    /**
     * 受影响记录数日志阀值
     * var int
     */
    const LOG_AFFECTED_ROWS = 10000;

    /**
     * @var array
     */
    public $error = array('code' => 0, 'msg' => "");

    /**
     * @var array $globals
     */
    static $globals;

    /**
     * 指定强行读取主从数据库
     * @var string
     */
    public static $dbentry;

    /**
     * @var bool
     */
    public $isShowDbError = true;

    public $pool_server_connected;


    /**
     * Db_PDONEW constructor.
     * @param string $prefix
     */
    public function __construct($prefix = "mysql")
    {
        $this->prefix = $prefix;
        if (zbj_lib_Constant::RUNTIME_ENVIRONMENT == 'product') {
            $this->isShowDbError = false;
        }

        $this->checkPoolServerByPort();

    }

    /**
     * init
     * @param array $params
     * @param string $table
     */
    public function init($params = array(), $table = '')
    {
        if (!empty($params['dbinfo'])) {
            $section_name = $params['dbinfo'];
            $table_array = array();
        } else {
            $table_array = explode('_', $table);
            $this->pri = $table_array[0];
            switch ($this->pri) {
                default:
                    $section_name = $this->pri;
            }
        }
        if (!empty($params['type'])) {
            $type = $params['type'];
        } else {
            $type = 'main';
        }
        $this->dtype = $type;

        //如果设置了强制入口
        if (!empty(self::$dbentry)) {
            $this->dtype = $type = self::$dbentry;
        }


        $dbConfig = SDb::getConfig($section_name, $type);
        if (!empty($dbConfig)) {
            //2011.9.1
            //默认端口,避免被上次数据库端口覆盖
            if (!isset($dbConfig['port'])) {
                $dbConfig['port'] = '3306';
            }
            foreach ($dbConfig as $key => $value) {
                $this->$key = $value;
            }
            $this->key = $this->prefix . ':' . $this->host . ':' . $this->port . ':' . $this->user . ':' . $type . ':' . $table_array[0];
            if (!isset(Db_PDONEW::$globals[$this->key])) {
                Db_PDONEW::$globals[$this->key] = "";
            }
        } else {
            $log_data = array(
                'table' => $table,
                'dbinfo' => $section_name,
                'params' => $params,
            );
            $this->logSQLContext($log_data, 'configuration.log');
        }

        $this->debugMessage(PHP_EOL . "SelectDB[{$this->key}], table[{$table}], params[ " . json_encode($params) . ']' . PHP_EOL);
    }

    /**
     * is count
     *
     * @param boolean $count
     */
    public function setCount($count)
    {
        if ($count == true) {
            $this->count = true;
        } else {
            $this->count = false;
        }
    }

    /**
     * page number
     *
     * @param int $page
     */
    public function setPage($page)
    {
        if (!is_numeric($page) || $page < 1) {
            $page = 1;
        }
        $this->page = $page;
    }

    /**
     * page size
     *
     * @param int $limit 0 is all
     */
    public function setLimit($limit)
    {
        if (!is_numeric($limit) || $limit < 0) {
            $limit = 0;
        }
        $this->limit = $limit;
    }

    /**
     * group by sql
     *
     * @param string $group_by
     * eg:    setGroupby("groupby MusicID");
     *      setGroupby("groupby MusicID,MusicName");
     */
    /**
     * @param string $group_by 含GROUP BY
     */
    public function setGroupby($group_by)
    {
        $this->groupby = $group_by;
    }

    /**
     * order by sql
     *
     * @param string $order_by
     * eg:    setOrderby("order by MusicID Desc");
     */
    public function setOrderby($order_by)
    {
        $this->orderby = $order_by;
    }

    /**
     * select data from db
     *
     * @param $table
     * @param string|array $condition
     * @param string|array $item
     * @param string $group_by
     * @param string $order_by
     * @param string $left_join
     * @param array $params
     * @return bool|DbData
     */
    public function select(
        $table,
        $condition = "",
        $item = "*",
        $group_by = "",
        $order_by = "",
        $left_join = "",
        $params = array('type' => 'query')
    ) {
        //{{{$item
        if ($item == "") {
            $item = "*";
        }
        if (is_array($table)) {
            $tmp = array();
            for ($i = 0; $i < count($table); $i++) {
                $tmp[] = trim($table[$i]);
            }
            $table = implode(" , ", $tmp);
        } else {
            $table = trim($table);
        }

        if (is_array($item)) {
            $item = implode(" , ", $item);
        }
        //}}}
        //{{{$condition
        $condition_string = $this->__quote($condition, "AND", $bind);

        if ($condition_string != "") {
            $condition_string = " WHERE " . $condition_string;
        }
        //}}}
        //{{{
        $join = "";
        if (is_array($left_join)) {
            foreach ($left_join as $key => $value) {
                $join .= " LEFT JOIN $key ON $value ";
            }
        }
        //}}}
        //{{{
        $this->groupby = $group_by != "" ? $group_by : $this->groupby;
        $this->orderby = $order_by != "" ? $order_by : $this->orderby;

        $order_by_sql = "";
        $order_by_sql_tmp = array();
        if (is_array($order_by)) {
            foreach ($order_by as $key => $value) {
                if (!is_numeric($key)) {
                    $order_by_sql_tmp[] = $key . " " . $value;
                }
            }
        } else {
            $order_by_sql = $this->orderby;
        }
        if (count($order_by_sql_tmp) > 0) {
            $order_by_sql = " ORDER BY " . implode(",", $order_by_sql_tmp);
        }
        //}}}

        $limit = "";
        if ($this->limit != 0) {
            $limit = ($this->page - 1) * $this->limit;
            $limit = "LIMIT {$limit}, {$this->limit}";
        }
        $this->sql = "SELECT {$item} FROM {$table} {$join} {$condition_string} {$group_by} {$order_by_sql} {$limit}";
        //echo $this->sql."<br>";
        //echo $this->sql;

        if ($group_by) {
            $this->countsql = "SELECT count(1) totalSize FROM (SELECT 1 FROM {$table} {$join} {$condition_string}"
                . " {$group_by}) as tmp_count";
        } else {
            $this->countsql = "SELECT count(1) totalSize FROM {$table} {$join} {$condition_string} {$group_by}";
        }


        $data = new DbData;

        $data->page = $this->page;
        $data->limit = $this->limit;
        $start = microtime(true);


        $data->limit = $this->limit;
        $data->items = $this->query($table, $this->sql, $bind, null, $params);
        if ($data->items === false) {
            //查询失败
            return false;
        }
        $data->pageSize = count($data->items);
        $end = microtime(true);
        $data->totalSecond = $end - $start;

        //}}}


        //{{{
        if ($this->limit != 0 && $this->count == true && $this->countsql != "") {
            $result_count = $this->query($table, $this->countsql, $bind, null, $params);
            $data->totalSize = $result_count[0]['totalSize'];
            $data->totalPage = ceil($data->totalSize / $data->limit);
        }
        //}}}

        //靠
        $this->setCount(false);
        $this->setPage(1);
        $this->setLimit(0);
        $this->setGroupby("");
        $this->setOrderby("");

        return $data;
    }

    /**
     * select one
     *
     * @param string $table
     * @param string|array $condition
     * @param string|array $item
     * @param string $group_by
     * @param string $order_by
     * @param string $left_join
     * @param array $params
     * @return array|bool
     */
    function selectOne(
        $table,
        $condition = "",
        $item = "*",
        $group_by = "",
        $order_by = "",
        $left_join = "",
        $params = array('type' => 'query')
    ) {
        $this->setLimit(1);
        $this->setCount(false);
        $data = $this->select($table, $condition, $item, $group_by, $order_by, $left_join, $params);

        //靠
        $this->setCount(false);
        $this->setPage(1);
        $this->setLimit(0);
        $this->setGroupby("");
        $this->setOrderby("");


        //2011.7.5 当查询失败才返回false,否则返回空
        if ($data === false) {
            return false;
        } else {
            if (isset($data->items[0])) {
                return $data->items[0];
            } else {
                return array();
            }
        }

    }

    /**
     * update data
     *
     * update("table",array('name'=>'myName','password'=>'myPass'),array('id'=>1));
     * update("table",array('name'=>'myName','password'=>'myPass'),array("password=$myPass"));
     * @param string $table
     * @param string|array $condition
     * @param string|array $item
     * @param array $params
     * @return bool|int
     */
    function update($table, $condition = "", $item = "", $params = array('type' => 'main'))
    {
        $value = $this->__quote($item, ",", $bind_v);

        $condition_string = $this->__quote($condition, "AND", $bind_c);
        if ($condition_string != "") {
            $condition_string = " WHERE " . $condition_string;
        }

        //2011.7.19 拒绝整表更新
        if (empty($condition_string)) {
            return false;
        }

        $this->sql = "UPDATE {$table} SET {$value} {$condition_string}";

        //echo $this->sql;
        if ($this->query($table, $this->sql, $bind_v, $bind_c, $params) !== false) {
            return $this->rowCount();
        } else {
            return false;
        }
    }

    /**
     * delete
     *
     * delete("table",array('name'=>'myName','password'=>'myPass'),array('id'=>1));
     * delete("table",array('name'=>'myName','password'=>'myPass'),array("password=$myPass"));
     * @param string $table
     * @param string|array $condition
     * @param array $params
     * @return bool|int
     */
    function delete($table, $condition = "", $params = array('type' => 'main'))
    {
        $condition_string = $this->__quote($condition, "AND", $bind);
        if ($condition_string != "") {
            $condition_string = " WHERE " . $condition_string;
        }

        //2011.7.19 拒绝整表删除
        if (empty($condition_string)) {
            return false;
        }

        $this->sql = "DELETE FROM {$table} {$condition_string}";
        if ($this->query($table, $this->sql, $bind, null, $params) !== false) {
            return $this->rowCount();
        } else {
            return false;
        }
    }

    /**
     * insert
     *
     * insert into zone_user_online values(2,'','','','',now(),now()) on duplicate key update onlineactivetime=CURRENT_TIMESTAMP;
     *
     * @param string $table
     * @param string|array $item
     * @param bool $is_replace
     * @param bool $is_delayed
     * @param array $update
     * @param array $params
     * @return array|bool|int
     */
    function insert(
        $table,
        $item = "",
        $is_replace = false,
        $is_delayed = false,
        $update = array(),
        $params = array('type' => 'main')
    ) {
        if ($is_replace == true) {
            $command = "REPLACE";
        } else {
            $command = "INSERT";
        }
        if ($is_delayed == true) {
            $command .= " DELAYED ";
        }

        $f = $this->__quote($item, ",", $bind_f);

        $this->sql = "$command INTO $table SET $f ";
        $v = $this->__quote($update, ",", $bind_v);
        if (!empty($v)) {
            $this->sql .= "ON DUPLICATE KEY UPDATE " . $v;
        }
        $r = $this->query($table, $this->sql, $bind_f, $bind_v, $params);
        if ($r === false) {        //2010.10.2 联系插入数据存在BUG，新增如果插入失败，返回false,
            return false;
        } elseif ($this->lastInsertId() > 0) {
            return $this->lastInsertId();
        } elseif ($this->affectedRows > 0) {
            return $this->affectedRows;
        } else {
            return $r;
        }
    }

    /**
     * query
     * @param string $table
     * @param string $sql
     * @param array $bind1
     * @param array $bind2
     * @param array $params
     * @return array|bool
     */
    function query($table, $sql, $bind1 = array(), $bind2 = array(), $params = array())
    {
        //{{{

        $this->debugMessage("SQL:$sql\n", $bind1, $bind2, $params);

        if (empty($sql)) {
            //执行SQL不能为空
            return false;
        }

        //检查sql安全性
        if (!$this->isSafe($sql)) {
            //sql存在风险
            return false;
        }

        //2010.12.28 增加查询时加锁模式
        $lock = isset($params['lock']) ? ' ' . $params['lock'] : '';
        $stmt = $this->getPodObject($table, $params)->prepare($sql . $lock);


        if (!$stmt) {
            $this->error['code'] = Db_PDONEW::$globals[$this->key]->errorCode();
            if ($this->isShowDbError) {
                $this->error['msg'] = Db_PDONEW::$globals[$this->key]->errorInfo();
            } else {
                $this->error['msg'] = "mysql error";
                $this->addLog('Url:' . $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'] . ' mysqlerror:' . json_encode(Db_PDONEW::$globals[$this->key]->errorInfo()));
            }
            $this->debugMessage('<span style="color:red;">', $this->error, '</span>');
            return false;
        }
        if (!empty($bind1)) {
            foreach ($bind1 as $k => $v) {
                $stmt->bindValue($k, $v);
            }
        }
        if (!empty($bind2)) {
            foreach ($bind2 as $k => $v) {
                $stmt->bindValue($k + count($bind1), $v);
            }
        }
        try {
            $exec_result = $stmt->execute();
        } catch (Exception $e) {
        }
        if ($exec_result) {
            $affected_rows = $this->affectedRows = $stmt->rowCount();
            if ($affected_rows >= self::LOG_AFFECTED_ROWS) {
                $log_data = array(
                    'table' => $table,
                    'sql' => $sql,
                    'affected_rows' => $affected_rows,
                    'bind1' => $bind1,
                    'bind2' => $bind2,
                    'params' => $params,
                );
                $this->logSQLContext($log_data, 'performance.log');
            }

            try {
                $rtn = $stmt->fetchAll(PDO::FETCH_ASSOC);
            } catch (Exception $e) {
                var_dump($e->getMessage());
            }

            return $rtn;

        } else {
            $this->error['code'] = $stmt->errorCode();
            if ($this->isShowDbError) {
                $this->error['msg'] = $stmt->errorInfo();
            } else {
                $this->error['msg'] = "mysql error";
                $this->addLog('Url:' . $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'] . ' mysqlerror:' . json_encode($stmt->errorInfo()));
            }
            $this->debugMessage('<span style="color:red;">', $this->error, '</span>');
        }

        return false;

    }

    /**
     * get last insert id
     * @return int
     */
    public function lastInsertId()
    {
        return Db_PDONEW::$globals[$this->key]->lastInsertId();
    }

    /**
     * @return int
     */
    public function rowCount()
    {
        return $this->affectedRows;
    }

    /**
     * @param string $sql
     * @param string $table
     * @return array|bool
     */
    public function execute($sql, $table = '')
    {
        return $this->query($table, $sql);
    }

    public function __connect($forceReconnect = false)
    {
        if (empty(Db_PDONEW::$globals[$this->key]) || $forceReconnect) {
            if (!empty(Db_PDONEW::$globals[$this->key])) {
                unset(Db_PDONEW::$globals[$this->key]);
            }
            try {
                if (extension_loaded('connect_pool') && $this->pool_server_connected == true) {
                    $driver = "PDOProxy";
                } else {
                    $driver = "PDO";
                }
                Db_PDONEW::$globals[$this->key] = new $driver($this->prefix . ":dbname=" . $this->database . ";host=" . $this->host . ";port=" . $this->port,
                    $this->user, $this->password);

                $this->debugMessage("new connect" . PHP_EOL);

            } catch (Exception $e) {

                //die("connect database error:\n".var_export($this,true));
                //写入日志
                $this->addLog('Host:' . $_SERVER['SERVER_NAME'] . ' Url:' . $_SERVER['REQUEST_URI'] . ' connect database error :' . $this->database . ',' . $this->dtype . ',' . $e->getMessage());

                //测试环境
                //die('connect database error :' .$this->database.','.$this->dtype.'');

                //生产环境
                zbj_lib_BaseUtils::httpStatus(500);
                die('<p align="center"><img src="http://t5.zbjimg.com/r/page/404_03.gif" border="0" /></p>');
            }
        }
        if (!empty($this->charset)) {
            try {
                Db_PDONEW::$globals[$this->key]->exec("SET NAMES " . $this->charset);
            } catch (Exception $e) {

                if (extension_loaded('connect_pool')) {

                    //pool服务正常,但无法连接DB,写入日志
                    $logStr = 'Host:' . $_SERVER['SERVER_NAME'] . ' Url:' . $_SERVER['REQUEST_URI']
                    . 'db error :' . $this->database . ',' . $this->dtype . ',' . $e->getMessage();

                    //写入日志
                    $this->addLog($logStr);

                    //生产环境
                    zbj_lib_BaseUtils::httpStatus(500);
                    die('<p align="center"><img src="http://t5.zbjimg.com/r/page/404_03.gif" border="0" /></p>');

                }

            }

        }
    }

    public function __quote($condition, $split = "AND", &$bind)
    {

        $condiStr = "";
        if (!is_array($bind)) {
            $bind = array();
        }
        if (is_array($condition)) {
            $v1 = array();
            $i = 1;
            foreach ($condition as $k => $v) {
                if (!is_numeric($k)) {
                    if (strpos($k, ".") > 0) {
                        $v1[] = "$k = ?";
                    } else {
                        $v1[] = "`$k` = ?";
                    }
                    $bind[$i++] = $v;
                } else {
                    $v1[] = ($v);
                }
            }
            if (count($v1) > 0) {
                $condiStr = implode(" " . $split . " ", $v1);

            }
        } else {
            $condiStr = $condition;
        }
        $this->getFilter($condiStr);//by 哪吒 2016-03-23
        return $condiStr;
    }

    /**
     * @param string $table
     * @param array $params
     * @return PDO
     */
    public function getPodObject($table, $params = array('type' => 'query'))
    {
        //print_r($params);
        if (empty($params['dbinfo'])) {
            $this->init($params, $table);
            if (empty(Db_PDONEW::$globals[$this->key])) {
                //echo "建立新连接 \n <br>";
                $this->__connect(true);
            } else {

                $this->debugMessage("connect state : " . PHP_EOL,
                    Db_PDONEW::$globals[$this->key]->getAttribute(PDO::ATTR_CONNECTION_STATUS));

                //如果已经有连接，检查连接状态
                /*
                if(!Db_PDONEW::$globals[$this->key]->getAttribute(PDO::ATTR_CONNECTION_STATUS)) {

                    //强制重新连接
                    $this->debugMessage("原连接断开，重新重新连接 \n <br>");

                    $this->__connect(true);
                }
                 */
            }
        } else {
            $this->init($params, $table);
            $this->__connect(true);
        }

        //var_dump(Db_PDONEW::$globals[$this->key]->getAttribute(PDO::ATTR_CONNECTION_STATUS));

        //echo $this->key . " \n<br>";

        return Db_PDONEW::$globals[$this->key];

    }

    /**
     * 开始事务
     *
     * @param string $table
     * @param array $params
     * @return bool
     */
    public function beginTransaction($table, $params = array('type' => 'main'))
    {
        $this->setDbEntry();
        return $this->getPodObject($table, $params)->beginTransaction();
    }

    /**
     * 提交事务
     * @param string $table
     * @param array $params
     * @return bool
     */
    public function commit($table, $params = array('type' => 'main'))
    {
        return $this->getPodObject($table, $params)->commit();
    }

    /**
     * 回滚事务
     * @param string $table
     * @param array $params
     * @return bool
     */
    public function rollBack($table, $params = array('type' => 'main'))
    {
        return $this->getPodObject($table, $params)->rollBack();
    }

    /**
     * 强制指定读取主从数据库
     *
     * 一旦设置不论读写都指向了设置的数据库，请谨慎使用
     * 在model及service使用时，只有在第一次获取数据时有效
     *
     */
    public function setDbEntry()
    {
        self::$dbentry = 'main';
    }

    /**
     * 写入日志文件 检查文件如果存在就建立日志
     *
     * @param string $msg
     * @param string $file
     * @return bool
     */
    public function addLog($msg, $file = 'db_error.log')
    {
        $dir = '/var/log/zhubajie/dberror/';
        $file = $dir . $file . '.' . date('Y-m-d');
        if ((is_dir($dir) || @mkdir($dir, 0755, true)) && is_writable($dir)) {
            $data = 'Date:' . date('Y-m-d H:i:s') . ' ' . $msg . "\n";
            $f = fopen($file, 'a+');
            fwrite($f, $data, strlen($data));
            fclose($f);
            return true;
        }
        return false;
    }

    /**
     * 断开所有链接
     * @return void
     */
    public function disconnect()
    {
        //若为连接池方式调用,主动将持有的连接放回池子里
        if (extension_loaded('connect_pool') && is_array(Db_PDONEW::$globals) && !empty(Db_PDONEW::$globals)) {
            foreach (Db_PDONEW::$globals as $v) {
                if (is_object($v)) {
                    $v->release();
                }
            }
        }
        Db_PDONEW::$globals = null;
    }

    /**
     * 检查sql的是否安全
     * @param string $sql
     * @return bool
     */
    public function isSafe($sql)
    {

        $clean = '';
        $error = '';
        $old_pos = 0;
        $pos = -1;

        while (true) {
            $pos = strpos($sql, '\'', $pos + 1);
            if ($pos === false) {
                break;
            }
            $clean .= substr($sql, $old_pos, $pos - $old_pos);

            while (true) {
                $pos1 = strpos($sql, '\'', $pos + 1);
                $pos2 = strpos($sql, '\\', $pos + 1);
                if ($pos1 === false) {
                    break;
                } elseif ($pos2 == false || $pos2 > $pos1) {
                    $pos = $pos1;
                    break;
                }

                $pos = $pos2 + 1;
            }
            $clean .= '$s$';

            $old_pos = $pos + 1;
        }

        $clean .= substr($sql, $old_pos);

        $clean = trim(strtolower(preg_replace(array('~\s+~s'), array(' '), $clean)));

        //老版本的Mysql并不支持union，常用的程序里也不使用union，但是一些黑客使用它，所以检查它
        if (strpos($clean, ' union ') !== false && preg_match('~(^|[^a-z])union($|[^[a-z])~s', $clean) != 0) {
            $fail = true;
            $error = "union detect";
        } elseif (strpos($clean, '/*') > 2 || strpos($clean, '--') !== false || strpos($clean, '#') !== false) {
            //发布版本的程序可能比较少包括--,#这样的注释，但是黑客经常使用它们
            $fail = true;
            $error = "comment detect";
        } elseif (strpos($clean, ' sleep') !== false && preg_match('~(^|[^a-z])sleep($|[^[a-z])~s', $clean) != 0) {
            //这些函数不会被使用，但是黑客会用它来操作文件，down掉数据库
            $fail = true;
            $error = "slown down detect";
        } elseif (strpos($clean, 'benchmark') !== false && preg_match('~(^|[^a-z])benchmark($|[^[a-z])~s',
                $clean) != 0
        ) {
            $fail = true;
            $error = "slown down detect";
        } elseif (strpos($clean, 'load_file') !== false && preg_match('~(^|[^a-z])load_file($|[^[a-z])~s',
                $clean) != 0
        ) {
            $fail = true;
            $error = "file fun detect";
        } elseif (strpos($clean, 'into outfile') !== false && preg_match('~(^|[^a-z])into\s+outfile($|[^[a-z])~s',
                $clean) != 0
        ) {
            $fail = true;
            $error = "file fun detect";
            //}elseif (preg_match('~\([^)]*?select~s', $clean) != 0){
            //老版本的MYSQL不支持子查询，我们的程序里可能也用得少，但是黑客可以使用它来查询数据库敏感信息
            //	$fail = true;
            //	$error="sub select detect";
        }

        if (!empty($fail)) {
            //写入日志
            $this->addLog($error . ' ' . $_SERVER['REMOTE_ADDR'] . ' ' . $_SERVER['HTTP_USER_AGENT'] . ' ' . $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'] . ' SQL:' . $sql,
                "inject_{$_SERVER['HOSTNAME']}.log");
            return false;
        } else {
            return true;
        }
    }

    /*
     * @param string 字符串
     * 记录危险sql 进行安全分析 by 哪吒 2016-03-23
     */
    public function getFilter($str)
    {
        $getfilter = "\\<.+javascript:window\\[.{1}\\\\x|<.*=(&#\\d+?;?)+?>|<.*(data|src)=data:text\\/html.*>|\\b(alert\\(|confirm\\(|expression\\(|prompt\\(|benchmark\s*?\(.*\)|sleep\s*?\(.*\)|load_file\s*?\\()|<[a-z]+?\\b[^>]*?\\bon([a-z]{4,})\s*?=|^\\+\\/v(8|9)|\\b(chr|mid)\\b\\s*?([\\(\\)'\"\\d]+?=[\\(\\)'\"\\d]+?|[\\(\\)'\"a-zA-Z]+?=[\\(\\)'\"a-zA-Z]+?|>|<|\s+?[\\w]+?\\s+?\\bin\\b\\s*?\(|\\blike\\b\\s+?[\"'])|\\/\\*.*\\*\\/|<\\s*script\\b|\\bEXEC\\b|UNION.+?SELECT\s*(\(.+\)\s*|@{1,2}.+?\s*|\s+?.+?|(`|'|\").*?(`|'|\")\s*)|UPDATE\s*(\(.+\)\s*|@{1,2}.+?\s*|\s+?.+?|(`|'|\").*?(`|'|\")\s*)SET|INSERT\\s+INTO.+?VALUES|(SELECT|DELETE)@{0,2}(\\(.+\\)|\\s+?.+?\\s+?|(`|'|\").*?(`|'|\"))FROM(\\(.+\\)|\\s+?.+?|(`|'|\").*?(`|'|\"))|(CREATE|ALTER|DROP|TRUNCATE)\\s+(TABLE|DATABASE)";
        if (preg_match("/" . $getfilter . "/is", $str, $arr) == 1) {
            $log = array(
                'sql' => $str,
                'agent' => zbj_lib_BaseUtils::getStr($_SERVER['HTTP_USER_AGENT']),
                'ip' => zbj_lib_BaseUtils::getIp(),
                'time' => time(),
                'url' => zbj_lib_BaseUtils::getCurrentUrl(),
                'data' => $arr[0],
            );
            $file = 'risk_sql_log';
            $this->addLog(json_encode($log), $file);
        }
        return true;
    }

    /**
     * 记录SQL查询上下文
     *
     * @param array $data
     * @param string $filename
     * @return bool
     */
    private function logSQLContext($data, $filename)
    {
        if ($data && is_array($data) && $filename) {
            $data['url'] = zbj_lib_BaseUtils::getCurrentUrl();
            $data['time'] = time();
            $data['ip'] = zbj_lib_BaseUtils::getIp();
            $data['ua'] = zbj_lib_BaseUtils::getStr($_SERVER['HTTP_USER_AGENT']);
            return $this->addLog(json_encode($data), $filename);
        } else {
            return false;
        }
    }

    /**
     * debug message
     */
    private function debugMessage()
    {
        if (defined("DEBUG") && $this->isShowDbError === true) {
            $args = func_get_args();
            foreach ($args as $v) {
                if (is_string($v)) {
                    echo $v;
                } else {
                    var_dump($v);
                }
            }
            return true;
        }
        return false;
    }

    private function checkPoolServerByPort()
    {
        if (extension_loaded('connect_pool') && $this->pool_server_connected == true) {
            return true;
        }

        if (extension_loaded('connect_pool')) {
            $fp = @fsockopen('127.0.0.1', CP_DEFAULT_PDO_PORT, $err_no, $err_msg, 0.01);
            if ($fp) {
                $this->pool_server_connected = true;
                @fclose($fp);
            }

            return $fp ? true : false;
        } else {
            return false;
        }
    }


}
`

DB:
`;<?php exit(); ?>
[order]
main   =   host:10.0.0.2,port:3306,user:root,database:order,password:xxxxx,charset:utf8
query  =   host:10.0.0.2,port:3306,user:root,database:order,password:xxxxx,charset:utf8`

**Comment by GXhua** [comment]
$obj1 = new pdoProxy('mysql:host=192.168.1.19;dbname=mz_db','public_user',"1qa2ws3ed");
$rs = $obj1->query("select * from test limit 1000");
var_dump($rs->fetchAll()); 
$obj1->release();

$obj1->exec("update mz_user set passwd='1111111' where user_id=295");
$obj1->release();

die;
我写了这样的代码  是没问题的，应该是你的框架集成有问题

**Comment by lockfan** [comment]
sorry，刚才急着贴了所有代码上来，请测试以下代码


`        $db = new PDOProxy('mysql:dbname=zhubajie_market;host=172.20.20.2;port=3306', 'task_write', 'SyWM3v4632tKNDMd');
        $db->exec("SET NAMES utf8");

        $sql = "UPDATE mk_task SET `user_id` = ?  WHERE `task_id` = ?";
        $lock = isset($params['lock']) ? ' ' . $params['lock'] : '';
        $stmt = $db->prepare($sql . $lock);

        $stmt->bindValue(1, 39);
        $stmt->bindValue(2, 292);


        $stmt->execute();
        $stmt->fetchAll(PDO::FETCH_ASSOC);`

**Comment by GXhua** [comment]
弱弱的问一下   execute之后 的fetchAll是干啥？

**Comment by GXhua** [comment]
找到问题了  原生pdo 你设置下这个参数
$db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
也会报错，pdoProxy为了在代理进程里面拿到异常返回给客户端强行将这个配置加上了
所以会报错
但是正常代码不应该这么写吧  update数据excute之后  不应该fetchAll把

**Comment by lockfan** [comment]
额。。。忽略了这个问题，感谢帮助
