### ISSUE TITLE
安装完成提示 undefined symbol: msgpack_init_class in Unknown on line 0

### ISSUE THREAD

**Issue by wdd2007** [swoole/php-cp#39]
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/connect_pool.so' - /usr/lib64/php/modules/connect_pool.so: undefined symbol: msgpack_init_class in Unknown on line 0
```

PHP v7.0.9

**Comment by wdd2007** [comment]
`[root@a12 php-cp]# phpize
Configuring for:
PHP Api Version:         20151012
Zend Module Api No:      20151012
Zend Extension Api No:   320151012
[root@a12 php-cp]# ./configure
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables...
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib
checking for PHP extension directory... /usr/lib64/php/modules
checking for PHP installed headers prefix... /usr/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking for connect_pool support... yes, shared
checking PHP version... ok
checking ZTS... ok
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1966080
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for ar... ar
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
configure: creating ./config.status
config.status: creating config.h
config.status: executing libtool commands
[root@a12 php-cp]#
[root@a12 php-cp]#
[root@a12 php-cp]# make install
/bin/sh /root/php-cp/libtool --mode=compile cc  -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /root/php-cp/connect_pool.c -o connect_pool.lo
libtool: compile:  cc -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /root/php-cp/connect_pool.c  -fPIC -DPIC -o .libs/connect_pool.o
/root/php-cp/connect_pool.c:944: 警告：‘cp_add_fail_into_mem’定义后未使用
/root/php-cp/connect_pool.c: 在函数‘redis_proxy_connect’中:
/root/php-cp/include/php7_wrapper.h:328: 警告：dereferencing pointer ‘redis_ce.655’ does break strict-aliasing rules
/root/php-cp/connect_pool.c:760: 附注：initialized from here
/root/php-cp/connect_pool.c: 在函数‘pdo_proxy_connect’中:
/root/php-cp/include/php7_wrapper.h:328: 警告：dereferencing pointer ‘pdo_ce.587’ does break strict-aliasing rules
/root/php-cp/connect_pool.c:470: 附注：initialized from here
/bin/sh /root/php-cp/libtool --mode=compile cc  -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /root/php-cp/cpServer.c -o cpServer.lo
libtool: compile:  cc -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /root/php-cp/cpServer.c  -fPIC -DPIC -o .libs/cpServer.o
/root/php-cp/cpServer.c: 在函数‘cpListen’中:
/root/php-cp/cpServer.c:648: 警告：隐式声明函数‘inet_pton’
/bin/sh /root/php-cp/libtool --mode=compile cc  -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /root/php-cp/cpWorker.c -o cpWorker.lo
libtool: compile:  cc -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /root/php-cp/cpWorker.c  -fPIC -DPIC -o .libs/cpWorker.o
/root/php-cp/cpWorker.c: 在函数‘cpWorker_do_ping’中:
/root/php-cp/cpWorker.c:403: 警告：传递‘_zval_ptr_dtor’的第 1 个参数时在不兼容的指针类型间转换
/usr/include/php/Zend/zend_variables.h:112: 附注：需要类型‘struct zval *’，但实参的类型为‘struct zval **’
/bin/sh /root/php-cp/libtool --mode=compile cc  -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /root/php-cp/connect_pool_client.c -o connect_pool_client.lo
libtool: compile:  cc -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /root/php-cp/connect_pool_client.c  -fPIC -DPIC -o .libs/connect_pool_client.o
/root/php-cp/connect_pool_client.c: 在函数‘cpRedis_conn_pool_server’中:
/root/php-cp/include/php7_wrapper.h:328: 警告：dereferencing pointer ‘p_sock_le.550’ does break strict-aliasing rules
/root/php-cp/connect_pool_client.c:121: 附注：initialized from here
/root/php-cp/connect_pool_client.c: 在函数‘async_done’中:
/root/php-cp/connect_pool_client.c:481: 警告：此函数中的‘cli’在使用前可能未初始化
/root/php-cp/connect_pool_client.c: 在函数‘zim_pdo_connect_pool_done’中:
/root/php-cp/connect_pool_client.c:1185: 警告：此函数中的‘zres’在使用前可能未初始化
/root/php-cp/connect_pool_client.c:1185: 警告：此函数中的‘source_zval’在使用前可能未初始化
/root/php-cp/connect_pool_client.c: 在函数‘release_worker’中:
/root/php-cp/include/php7_wrapper.h:328: 警告：dereferencing pointer ‘p_sock_le.554’ does break strict-aliasing rules
/root/php-cp/connect_pool_client.c:150: 附注：initialized from here
/root/php-cp/connect_pool_client.c: 在函数‘zim_pdo_connect_pool___call’中:
/root/php-cp/include/php7_wrapper.h:328: 警告：dereferencing pointer ‘p_sock_le.550’ does break strict-aliasing rules
/root/php-cp/connect_pool_client.c:121: 附注：initialized from here
/bin/sh /root/php-cp/libtool --mode=compile cc  -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /root/php-cp/cpFunction.c -o cpFunction.lo
libtool: compile:  cc -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /root/php-cp/cpFunction.c  -fPIC -DPIC -o .libs/cpFunction.o
/bin/sh /root/php-cp/libtool --mode=compile cc  -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /root/php-cp/cpMemory.c -o cpMemory.lo
libtool: compile:  cc -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /root/php-cp/cpMemory.c  -fPIC -DPIC -o .libs/cpMemory.o
/bin/sh /root/php-cp/libtool --mode=compile cc  -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /root/php-cp/cpNetWork.c -o cpNetWork.lo
libtool: compile:  cc -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /root/php-cp/cpNetWork.c  -fPIC -DPIC -o .libs/cpNetWork.o
/bin/sh /root/php-cp/libtool --mode=compile cc  -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /root/php-cp/cpClientNet.c -o cpClientNet.lo
libtool: compile:  cc -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /root/php-cp/cpClientNet.c  -fPIC -DPIC -o .libs/cpClientNet.o
/root/php-cp/cpClientNet.c: 在函数‘swClient_inet_addr’中:
/root/php-cp/cpClientNet.c:108: 警告：隐式声明函数‘inet_aton’
/bin/sh /root/php-cp/libtool --mode=compile cc  -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /root/php-cp/cpPingWorker.c -o cpPingWorker.lo
libtool: compile:  cc -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /root/php-cp/cpPingWorker.c  -fPIC -DPIC -o .libs/cpPingWorker.o
/root/php-cp/cpPingWorker.c: 在函数‘cpPing_add_dislist’中:
/root/php-cp/cpPingWorker.c:32: 警告：隐式声明函数‘cp_ser_and_setdis’
/bin/sh /root/php-cp/libtool --mode=compile cc  -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /root/php-cp/msgpack/msgpack.c -o msgpack/msgpack.lo
libtool: compile:  cc -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /root/php-cp/msgpack/msgpack.c  -fPIC -DPIC -o msgpack/.libs/msgpack.o
/bin/sh /root/php-cp/libtool --mode=compile cc  -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /root/php-cp/msgpack/msgpack_pack.c -o msgpack/msgpack_pack.lo
libtool: compile:  cc -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /root/php-cp/msgpack/msgpack_pack.c  -fPIC -DPIC -o msgpack/.libs/msgpack_pack.o
/root/php-cp/msgpack/msgpack_pack.c:30:1: 警告：多行注释
/bin/sh /root/php-cp/libtool --mode=compile cc  -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /root/php-cp/msgpack/msgpack_unpack.c -o msgpack/msgpack_unpack.lo
libtool: compile:  cc -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /root/php-cp/msgpack/msgpack_unpack.c  -fPIC -DPIC -o msgpack/.libs/msgpack_unpack.o
/bin/sh /root/php-cp/libtool --mode=compile cc  -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /root/php-cp/msgpack/msgpack_convert.c -o msgpack/msgpack_convert.lo
libtool: compile:  cc -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /root/php-cp/msgpack/msgpack_convert.c  -fPIC -DPIC -o msgpack/.libs/msgpack_convert.o
/bin/sh /root/php-cp/libtool --mode=compile cc  -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /root/php-cp/msgpack7/msgpack.c -o msgpack7/msgpack.lo
libtool: compile:  cc -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /root/php-cp/msgpack7/msgpack.c  -fPIC -DPIC -o msgpack7/.libs/msgpack.o
/root/php-cp/msgpack7/msgpack.c: 在函数‘ps_srlzr_encode_msgpack’中:
/root/php-cp/msgpack7/msgpack.c:156: 警告：传递‘msgpack_serialize_zval’的第 1 个参数时在不兼容的指针类型间转换
/root/php-cp/msgpack7/msgpack_pack.h:21: 附注：需要类型‘struct instead_smart *’，但实参的类型为‘struct smart_str *’
/root/php-cp/msgpack7/msgpack.c: 在文件层：
/root/php-cp/msgpack7/msgpack/unpack_template.h:91: 警告：‘template_data’定义后未使用
/bin/sh /root/php-cp/libtool --mode=compile cc  -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /root/php-cp/msgpack7/msgpack_pack.c -o msgpack7/msgpack_pack.lo
libtool: compile:  cc -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /root/php-cp/msgpack7/msgpack_pack.c  -fPIC -DPIC -o msgpack7/.libs/msgpack_pack.o
/root/php-cp/msgpack7/msgpack_pack.c: 在函数‘msgpack_serialize_zval’中:
/root/php-cp/msgpack7/msgpack_pack.c:417: 警告：此函数中的‘var_already’在使用前可能未初始化
/bin/sh /root/php-cp/libtool --mode=compile cc  -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /root/php-cp/msgpack7/msgpack_unpack.c -o msgpack7/msgpack_unpack.lo
libtool: compile:  cc -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /root/php-cp/msgpack7/msgpack_unpack.c  -fPIC -DPIC -o msgpack7/.libs/msgpack_unpack.o
/root/php-cp/msgpack7/msgpack/unpack_template.h:70: 警告：‘template_init’定义后未使用
/root/php-cp/msgpack7/msgpack/unpack_template.h:91: 警告：‘template_data’定义后未使用
/root/php-cp/msgpack7/msgpack/unpack_template.h:97: 警告：‘template_execute’定义后未使用
/bin/sh /root/php-cp/libtool --mode=compile cc  -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2   -c /root/php-cp/msgpack7/msgpack_convert.c -o msgpack7/msgpack_convert.lo
libtool: compile:  cc -I. -I/root/php-cp -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include -DHAVE_CONFIG_H -Wall -pthread -g -O2 -c /root/php-cp/msgpack7/msgpack_convert.c  -fPIC -DPIC -o msgpack7/.libs/msgpack_convert.o
/root/php-cp/msgpack7/msgpack_convert.c: 在函数‘msgpack_convert_object’中:
/root/php-cp/msgpack7/msgpack_convert.c:293: 警告：此函数中的‘function_name’在使用前可能未初始化
/bin/sh /root/php-cp/libtool --mode=link cc -DPHP_ATOM_INC -I/root/php-cp/include -I/root/php-cp/main -I/root/php-cp -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/root/php-cp/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O2  -lpthread -o connect_pool.la -export-dynamic -avoid-version -prefer-pic -module -rpath /root/php-cp/modules  connect_pool.lo cpServer.lo cpWorker.lo connect_pool_client.lo cpFunction.lo cpMemory.lo cpNetWork.lo cpClientNet.lo cpPingWorker.lo msgpack/msgpack.lo msgpack/msgpack_pack.lo msgpack/msgpack_unpack.lo msgpack/msgpack_convert.lo msgpack7/msgpack.lo msgpack7/msgpack_pack.lo msgpack7/msgpack_unpack.lo msgpack7/msgpack_convert.lo
libtool: link: cc -shared  .libs/connect_pool.o .libs/cpServer.o .libs/cpWorker.o .libs/connect_pool_client.o .libs/cpFunction.o .libs/cpMemory.o .libs/cpNetWork.o .libs/cpClientNet.o .libs/cpPingWorker.o msgpack/.libs/msgpack.o msgpack/.libs/msgpack_pack.o msgpack/.libs/msgpack_unpack.o msgpack/.libs/msgpack_convert.o msgpack7/.libs/msgpack.o msgpack7/.libs/msgpack_pack.o msgpack7/.libs/msgpack_unpack.o msgpack7/.libs/msgpack_convert.o   -lpthread  -pthread   -pthread -Wl,-soname -Wl,connect_pool.so -o .libs/connect_pool.so
libtool: link: ( cd ".libs" && rm -f "connect_pool.la" && ln -s "../connect_pool.la" "connect_pool.la" )
/bin/sh /root/php-cp/libtool --mode=install cp ./connect_pool.la /root/php-cp/modules
libtool: install: cp ./.libs/connect_pool.so /root/php-cp/modules/connect_pool.so
libtool: install: cp ./.libs/connect_pool.lai /root/php-cp/modules/connect_pool.la
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/sbin" ldconfig -n /root/php-cp/modules
----------------------------------------------------------------------
Libraries have been installed in:
   /root/php-cp/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
Installing shared extensions:     /usr/lib64/php/modules/`

**Comment by Minglong** [comment]
I also have this problem. anyone fix it?

**Comment by Minglong** [comment]
有人解决了这个问题了吗？

**Comment by GXhua** [comment]
启动的时候报这个错对吗？

**Comment by GXhua** [comment]
不好意思才注意到这个issue  已经修复并提交到master分支 请测试
