### ISSUE TITLE
多个请求的连接可以重复使用吗？

### ISSUE THREAD

**Issue by robbinhan** [swoole/php-cp#4]
我想问下，这个扩展的连接池，是可以重复使用的吗，比方有两个请求，第一个请求连了redis和mysql，将其放入连接池，然后请求结束，第二个请求是否直接可以使用第一个的连接，而不用重新开启连接

**Comment by GXhua** [comment]
当然会重用上次的连接 这是连接池的最基本功能，只要放入池子（也就是调用release或者请求结束），其他的进程就会去用了。

**Comment by robbinhan** [comment]
OK，那请问是否真的使用默认数据会有问题，必须select(n)才行？

**Comment by GXhua** [comment]
默认的也没问题，之前有个朋友提了issue，说必须select，但是我没有重现他所说的问题。

**Comment by molibei** [comment]
这个问题在重新pull了后已经解决了
