### ISSUE TITLE
./php_connect_pool.h:32:10: fatal error: 'sys/epoll.h' file not found #include <sys/epoll.h> //todo

### ISSUE THREAD

**Issue by ehvu** [swoole/php-cp#40]
/bin/sh /Users/nate/Downloads/php-cp-1.4.8/libtool --mode=compile cc  -I. -I/Users/nate/Downloads/php-cp-1.4.8 -DPHP_ATOM_INC -I/Users/nate/Downloads/php-cp-1.4.8/include -I/Users/nate/Downloads/php-cp-1.4.8/main -I/Users/nate/Downloads/php-cp-1.4.8 -I/usr/local/Cellar/php54/5.4.45_4/include/php -I/usr/local/Cellar/php54/5.4.45_4/include/php/main -I/usr/local/Cellar/php54/5.4.45_4/include/php/TSRM -I/usr/local/Cellar/php54/5.4.45_4/include/php/Zend -I/usr/local/Cellar/php54/5.4.45_4/include/php/ext -I/usr/local/Cellar/php54/5.4.45_4/include/php/ext/date/lib -I/Users/nate/Downloads/php-cp-1.4.8/include  -DHAVE_CONFIG_H  -Wall -pthread -g -O0   -c /Users/nate/Downloads/php-cp-1.4.8/connect_pool.c -o connect_pool.lo 
mkdir .libs
 cc -I. -I/Users/nate/Downloads/php-cp-1.4.8 -DPHP_ATOM_INC -I/Users/nate/Downloads/php-cp-1.4.8/include -I/Users/nate/Downloads/php-cp-1.4.8/main -I/Users/nate/Downloads/php-cp-1.4.8 -I/usr/local/Cellar/php54/5.4.45_4/include/php -I/usr/local/Cellar/php54/5.4.45_4/include/php/main -I/usr/local/Cellar/php54/5.4.45_4/include/php/TSRM -I/usr/local/Cellar/php54/5.4.45_4/include/php/Zend -I/usr/local/Cellar/php54/5.4.45_4/include/php/ext -I/usr/local/Cellar/php54/5.4.45_4/include/php/ext/date/lib -I/Users/nate/Downloads/php-cp-1.4.8/include -DHAVE_CONFIG_H -Wall -pthread -g -O0 -c /Users/nate/Downloads/php-cp-1.4.8/connect_pool.c  -fno-common -DPIC -o .libs/connect_pool.o
In file included from /Users/nate/Downloads/php-cp-1.4.8/connect_pool.c:17:
./php_connect_pool.h:32:10: fatal error: 'sys/epoll.h' file not found
#include <sys/epoll.h> //todo
         ^
1 error generated.
make: *** [connect_pool.lo] Error 1

**Comment by GXhua** [comment]
请使用linux系统
