### ISSUE TITLE
没有测试并发，一个请求访问效率减半？是否打开姿势不对？

### ISSUE THREAD

**Issue by SingoWong** [swoole/php-cp#41]
这里的library中redispool和redis基本一样，redispool中构建对象是使用new redisProxy()，pool.ini没改，用了默认的配置，执行结果redis: 1123ms， redispool: 2303
<?php
class Demo extends CI_Controller
{
        public function __construct()
        {
                parent::__construct();
        }

```
    public function index() {
            phpinfo();
    }

    public function org() {
            $start = $this->getMillisecond();
            $this->load->library('redis');

            for ($i=0; $i<10000; $i++) {
                    $this->redis->hset("POOL1", $i, time());
            }
            $this->redis->hgetall("POOL1");
            $end = $this->getMillisecond();
            echo "done ".($end-$start);
    }

    public function pool() {
            $start = $this->getMillisecond();
            $this->load->library('redispool');

            for ($i=0; $i<10000; $i++) {
                    $this->redispool->hset("POOL1", $i, time());
            }
            $this->redispool->hgetall("POOL1");
            $end = $this->getMillisecond();
            echo "done ".($end-$start);
    }

    private function getMillisecond() {
            list($t1, $t2) = explode(' ', microtime());
            return (float)sprintf('%.0f',(floatval($t1)+floatval($t2))*1000);
    }
```

}

**Comment by GXhua** [comment]
这样的测试没有意义，你应该写个脚本 内容是50次以内的redis请求，然后用ab或者webbench压这个脚本看多少qps，因为现实的业务就是这样的

**Comment by GXhua** [comment]
对了 还要看redis的负载情况

**Comment by SingoWong** [comment]
感谢大神回复，我还有一个问题不是很明白，pool.ini中的链接配置需要在这里配置吗？如果我这里不配置在性能上主要影响在什么地方呢？


['mysql:host=192.168.1.19;dbname=mz_gay_group2;charset=utf8'];mysql配置
pool_min = 2
pool_max = 30

['mysql:host=192.168.1.19;dbname=mz_gay_group;charset=utf8'];mysql配置
pool_min = 2
pool_max = 30

['192.168.1.19:6379:0'];redis配置 ip:port:db号
pool_min = 2
pool_max = 30

**Comment by GXhua** [comment]
不配置的话就走默认的配置  没啥影响
