### ISSUE TITLE
不支持执行SET NAMES utf8 只能通过dsn传入连接编码？

### ISSUE THREAD

**Issue by yjqg6666** [swoole/php-cp#45]
$ cat /home/test/sql.php
\<? php
$pdo = new pdoProxy("mysql:dbname=db_test;host=db.com;port=3306", "db_user", "db_password");
var_dump($pdo);
$pdo->exec("SET NAMES utf8");
$rs = $pdo->query("show tables");
var_dump($rs->fetchAll());
$pdo->release();

CLI 执行会报Fatal error:

object(pdoProxy) # 1 (4) {
  ["use_ms"]=>
  bool(false)
  ["config"]=>
  array(1) {
    ["master"]=>
    array(3) {
      ["data_source"]=>
      string(65) "mysql:dbname=db_test;host=db.com;port=3306"
      ["username"]=>
      string(12) "db_user"
      ["pwd"]=>
      string(16) "db_password"
    }
  }
  ["in_tran"]=>
  bool(false)
  ["enable_slave"]=>
  bool(true)
}
PHP Fatal error:  Uncaught exception 'Exception' with message 'call pdo method error!' in /home/test/sql.php:4
Stack trace:
\# 0 /home/test/sql.php(4): pdoProxy->__call('exec', Array)
\# 1 /home/test/sql.php(4): pdoProxy->exec('SET NAMES utf8')
\# 2 {main}
  thrown in /home/test/sql.php on line 4

Fatal error: Uncaught exception 'Exception' with message 'call pdo method error!' in /root/sql.php:4
Stack trace:
 \# 0 /home/test/sql.php(4): pdoProxy->__call('exec', Array)
 \# 1 /home/test/sql.php(4): pdoProxy->exec('SET NAMES utf8')
 \# 2 {main}  thrown in /home/test/sql.php on line 4

错误抛出位置位于：

https://github.com/swoole/php-cp/blob/99502494d19df0a030d63a1ddc56bde4e36de5c2/connect_pool.c#L604

**Comment by GXhua** [comment]
对 目前是这样的

**Comment by yjqg6666** [comment]
$pdo->exec("SET NAMES utf8");  改成  $pdo->query("SET NAMES utf8");  
问题解决 

不知道为什么原生的PDO->exec("SET NAMES utf8");不会挂掉
