### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by zgs225** [swoole/php-cp#54]
<img width="929" alt="2016-12-19 22 53 18" src="https://cloud.githubusercontent.com/assets/3501131/21317108/ad2b356e-c63e-11e6-8b4f-990c48ebba20.png">

**Comment by Credochen** [comment]
`make install`的时候失败
> make: *** [connect_pool_client.lo] Error 1

![ee](https://cloud.githubusercontent.com/assets/960647/21380110/be00a702-c78d-11e6-8e1f-3086bd8458d1.jpg)

**Comment by GXhua** [comment]
已修复
