### ISSUE TITLE
pdo_connect_pool_PDOStatement::$queryString

### ISSUE THREAD

**Issue by yunwuxin** [swoole/php-cp#66]
PDOStatement 是有这个属性的 

pdo_connect_pool_PDOStatement 获取不到

**Comment by GXhua** [comment]
嗯  确实有这个问题，所有的属性应该都拿不到   phpcp的原理是代理执行pdo的方法  属性拿不到的

**Comment by yunwuxin** [comment]
pdo_connect_pool_PDOStatement   再实现个__get方法呢

**Comment by GXhua** [comment]
哦哦 对 没想到   狠狠的甩个pr过来？

**Comment by yunwuxin** [comment]
我不会 😄   
还是你来吧

**Comment by GXhua** [comment]
好的  我排期弄下

**Comment by bukn** [comment]
我把queryString加上了，一会儿提个pr
