### ISSUE TITLE
创建进程失败

### ISSUE THREAD

**Issue by collinsmao** [swoole/php-cp#7]
cpCreate_worker_mem: create sys v shm. Error: Inappropriate ioctl for device [25]	
cpServer_start: Fork worker process fail	

这是/tmp/log里的记录，还需要其他的信息吗?

**Comment by GXhua** [comment]
你本地的共享内存和cp的冲突了
ipcs -m | awk '$2 ~ /[0-9]+/ {print $2}' | while read s; do sudo ipcrm -m $s; done

用上面那个命令清下共享内存 再启动

**Comment by collinsmao** [comment]
多谢

**Comment by lscgzwd** [comment]
centos 6.6 X64出现相同问题

**Comment by GXhua** [comment]
用这个命令 ipcs -m | awk '$2 ~ /[0-9]+/ {print $2}' | while read s; do sudo ipcrm -m $s; done
清一下共享内存
