### ISSUE TITLE
一些明显的错误

### ISSUE THREAD

**Issue by lijianwei123** [swoole/php-cp#8]
cpNetwork.c:130中 handles\[EPOLL_CLOSE\](events\[i\].data.fd)
根本没有设置EPOLL_CLOSE方法
建议这里直接continue;

config.m4中没有检测epoll，造成未定义have_epoll，编译的时候报错的
加上 AC_CHECK_LIB(c, epoll_create, AC_DEFINE(HAVE_EPOLL, 1, [have epoll]))

**Comment by GXhua** [comment]
多谢提醒~   目前正在做kqueue和epoll的兼容  下个大版本发

**Comment by GXhua** [comment]
EPOLL_CLOSE的方法设置在cpServer.c的535行

**Comment by lijianwei123** [comment]
恩，我说的是master 的cpEpoll_wait
加个判断应该就可以了

**Comment by GXhua** [comment]
为啥要加 handles[EPOLL_CLOSE] != NULL 判断呢？这个项目里面handles[EPOLL_CLOSE]是肯定有值的啊

**Comment by lijianwei123** [comment]
目前没有的，如果对端关闭，会出现段错误的

**Comment by GXhua** [comment]
在cpServer.c的535行设置了值的呀，你那边现在出现coredump了？

**Comment by lijianwei123** [comment]
![image](https://cloud.githubusercontent.com/assets/5708237/6425746/8a260972-bf74-11e4-83f3-ccc1c79cfe10.png)

**Comment by GXhua** [comment]
还没等设置handles[EPOLL_CLOSE]的值 你就手动jump到这里了吧。。。，。。正常运行的时候这里发生过coredump吗？

**Comment by lijianwei123** [comment]
恩，理解了，不过我有个担心哈
在client连接的时候，有没有可能，不先走epollin,  而先触发EPOLLRDHUP | EPOLLERR | EPOLLHUP这些事件

**Comment by GXhua** [comment]
应该有这个可能
