### ISSUE TITLE
值为负的字段，读取后变成正值？这个bug有点重

### ISSUE THREAD

**Issue by Marchcn-Ben** [swoole/php-cp#87]
使用pdoProxy建立的连接 
$result = $mysqlConn -> query('select fenceId from users where userId = 5628');
$a = $result -> fetch();
print_r($a);
当fenceId为负值=-51时，居然溢出了变成了205！
再次尝试当fenceId=-999时，返回了25
使用正常的pdo均可正常返回负值

**Comment by GXhua** [comment]
用1.4.8版本
