### ISSUE TITLE
可能的内存泄露

### ISSUE THREAD

**Issue by lijianwei123** [swoole/php-cp#9]
1.  connect_pool_client.c中的
static int *workerid2writefd = NULL;
static int *workerid2readfd = NULL;
static void **semid2attbuf = NULL;
使用原生的calloc 
没有free
为什么不用pecalloc

2. 每个worker中创建的共享内存, 在回收worker并没有shmctl删除

**Comment by GXhua** [comment]
1,这块calloc的内存是一直会用到的，直到把这个php进程回收，os来回收内存，所以就没free，当然free了更严谨。
2、因为下个worker还会用到

**Comment by lijianwei123** [comment]
第一个我认同
第二个确实会被下个worker使用，不过还是建议pool_server_shutdown时候关闭ipc共享内存(worker和ping 进程) 不然如果开启100个worker进程，就会有500M左右的没有释放，如果下次启动的时候刚好端口换了，那这些内存不会被复用的。

**Comment by GXhua** [comment]
嗯 多谢反馈哈~  刚开始是管理进程来在worker退出后来删除共享内存的，但是此时fpm进程还在attach这块内存 如果直接删除的话会导致bug    具体啥现象我忘记了 你可以试下

**Comment by GXhua** [comment]
已经改为mmap来共享内存 来避免问题
